
[fonts]

# Controls font size
size = 20

family = "FiraCode Nerd Font"

# Prevents character combinations like this `!=` 
# from being displayed like this `≠`
features = ["-calt"]

# Ensures that emoji's like the cloud in `☁️ (us-east-1)`
# are displayed correctly
symbol-map = [
    { start = "2601", end = "2601", font-family = "Noto Color Emoji" }
]
#______________________________________________________________________________

[navigation]

# Hides Rio's tab navigation bar, 
# and turns off any Rio tab related bindings to avoid clashes with Zellij
mode = "Plain"
#______________________________________________________________________________

[colors]
background = "#000000"
#______________________________________________________________________________

[window.background-image]

# WARNING: 
# 1. Do not add a path to an image without setting the opacity first
# 2. Do not set the 

# Do not set path without an opacity value

opacity = 0.12
path = "/home/dezlymacauley/local-workspace/shared-assets/purple_mech.jpg"

#______________________________________________________________________________
